# General Settings
name: Sergei Velikanov
job_title: Developer, Team Leader, CTO
email: me@velikanov.pro
description: |
  I am a developer in broad sense of the term.<br />
  My belief is that one doesn't have to stick to one gun to be perfect shooter.<br />
  Flexibility over sedentary.<br />
  Extensibility over attachment.<br />
  Achievement over observation.
avatar: https://github.com/velikanov/velikanov.github.io/raw/master/assets/img/photo.png
favicon: /favicon.ico
twitter_handler: '@velikanovpro'
analytics_code: UA-58781157-1
disqus: velikanov-pro

# Certifications
certifications:
- { name: 'Zend Certified Engineer', image_url: 'https://www.zend.com/static-assets/img/zcedirectory/zce-2017-small.gif', url: 'https://www.zend.com/en/yellow-pages/ZEND030525' }
- { name: 'Certified Blockchain Expert', image_url: 'https://s3.amazonaws.com/accredible-api-badge/1499864542117.png', url: 'https://www.credential.net/hafc5zkn' }

# Social Accounts
social_networks:
-  { name: facebook, url: 'https://www.facebook.com/serge.velikanov' }
-  { name: linkedin, url: 'https://linkedin.com/sergevelikan' }
-  { name: twitter, url: 'https://twitter.com/velikanovpro' }
-  { name: github, url: 'https://github.com/velikanov' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: skype, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }

# Modules Settings
show_categories: 0
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://velikanov.pro"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed